### ISSUE TITLE
Bug for actiongrid buttons

### ISSUE THREAD

**Issue by radder** [leandrogehlen/yii2-treegrid#4]
HI, your treegrid has a bug.

Not correct url provided for ActionColumn(grid) buttons like view, edit, delete, etc..

Reason:
You get key from dataProvided when list is not sorted and put them for sorted list.

How to fix:
TreeGrid.php:
1) need to change  $key = $keys[$index]; on  $key = $model['id'];
2) remove $keys = $this->dataProvider->getKeys();(as not needed);

**Comment by kochs-online** [comment]
@radder is right. I noticed this bug as well.
Unfortunately @radder's bugfix relies on model's using the attribute 'id'. So that's not working out either.
I haven't fully understood yet how normalizeData() influences the order of the models, but maybe that's where things go wrong? Also keep in mind that array_values() makes a mess of ordered arrays (cp. PHP documentation [comment by biziclop](http://php.net/manual/de/function.array-values.php#114941)).

**Comment by leandrogehlen** [comment]
Sorry for delay!
The problem occurs because "normalizeData" is invoked after get keys. I have no  time to resolve this problem now. I will create tests to avoid another issues like.
The release 1.0.0 is working

**Comment by abdulquddus** [comment]
@radder  you save my day man. @leandrogehlen  First of all a very nice and cool widget.One more thing I am facing is more than two childs are not showing up. What could be holding this.

**Comment by kochs-online** [comment]
@abdulquddus: Have a look at #5. That issue might affect you if you mix different types for parent IDs (like strings and integers).
